language: ruby

rvm:
  - 2.2
  - 2.1

before_script:
 - export RAILS_ENV=default

gemfile:
  - Gemfile
  - gemfiles/fluentd_v0.10.gemfile
  - gemfiles/fluentd_v0.12.gemfile

# to avoid travis-ci issue since 2015-12-25
before_install:
  - gem update bundler

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/fluentd_v0.10.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/fluentd_v0.10.gemfile

